@echo off
echo Installing required dependencies...
call npm install --save-dev postcss postcss-preset-env autoprefixer
echo Downgrading Next.js to a stable version...
call npm install next@13.4.0
echo Creating .nojekyll file...
echo. > public\.nojekyll
echo All done! Now you can run "npm run deploy"
